name: 💡 Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make BingeAlert better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or frustration this feature would address
      placeholder: "I have multiple users who want different notification preferences, but right now everyone gets the same emails..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe your ideal solution
      placeholder: "A per-user settings page where each user can choose email frequency, notification types, etc."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would use regularly
        - Critical for my setup
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you found any workarounds or alternative approaches?
      placeholder: "I've been manually managing notification preferences by..."
    validations:
      required: false
